//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOnlineDatRipper.Properties
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        /// <summary>
        /// Defines the resourceMan.
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture.
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.....
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOnlineDatRipper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.....
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the acm_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap acm_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("acm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the app
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).....
        /// </summary>
        internal static System.Drawing.Icon app
        {
            get
            {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the dir_icon_closed
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap dir_icon_closed
        {
            get
            {
                object obj = ResourceManager.GetObject("dir_icon_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the dir_icon_opened
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap dir_icon_opened
        {
            get
            {
                object obj = ResourceManager.GetObject("dir_icon_opened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the extract_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap extract_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("extract_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the eye_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap eye_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("eye_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Fallout_Palette
        /// Looks up a localized resource of type System.Byte[].....
        /// </summary>
        internal static byte[] Fallout_Palette
        {
            get
            {
                object obj = ResourceManager.GetObject("Fallout_Palette", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        /// Gets the file_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap file_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("file_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the frm_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap frm_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("frm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the load_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap load_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("load_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the root_icon_closed
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap root_icon_closed
        {
            get
            {
                object obj = ResourceManager.GetObject("root_icon_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the root_icon_opened
        /// Looks up a localized resource of type System.Drawing.Bitmap.....
        /// </summary>
        internal static System.Drawing.Bitmap root_icon_opened
        {
            get
            {
                object obj = ResourceManager.GetObject("root_icon_opened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
